### PR TITLE
Fix Driver error on Windows

### PR DESCRIPTION
**Pull request by viteo**
* alt setting for Standard AS Interface Descriptor
* wTerminalType changed to Mic = 0x0201
* FREQ value to 3-byte value

### CODE REVIEW

**Comment by viteo** [comment]
i've cleaned up all other changes, left only significant for windows.
i've tested it on linux and windows, works like a charm.

**Comment by anonymou8** [comment]
Viktar, thank you for the pull request! I like the comments you've added to the `descriptors_audio.s`.

As I don't have a facility for live-testing the code for now, would you mind if I ask you a couple of things to try?

1. In the `usb_audio.c` file: what if we comment out lines [#411](https://github.com/anonymou8/stm32_usb_audio/blob/8bbd39be9ce847e85503d9603e999aa776704a4b/usb_audio.c#L411) and [#414](https://github.com/anonymou8/stm32_usb_audio/blob/8bbd39be9ce847e85503d9603e999aa776704a4b/usb_audio.c#L414)? The `current_configuration` variable is not used anywhere in the code so changing its value changes nothing; as for reading, its value also not used as `data` to be sent is overwritten on the next line #415.
2. In the `descriptors_audio.s`, line [#164](https://github.com/anonymou8/stm32_usb_audio/blob/8bbd39be9ce847e85503d9603e999aa776704a4b/descriptors_audio.s#L164), the `FREQ` descriptor parameter: what if we leave original `.4byte` definition but change the size of the descriptor subtracting 1 from it? Something like
       
                .4byte  FREQ                @; tSamFreq
            CSASF_SZ = . - csi_descriptor_as_fmt - 1

Will the device still work with these changes?

If you're going to change the PR, then maybe completely delete the `#if 1`/`#endif` preprocessor condition on line #418 as it doesn't really mean anything anymore.

Thank you.

**Comment by anonymou8** [comment]
There's also unused variable in the [`SET_INTERFACE`](https://github.com/anonymou8/stm32_usb_audio/blob/8bbd39be9ce847e85503d9603e999aa776704a4b/usb_audio.c#L421) and [`GET_INTERFACE`](https://github.com/anonymou8/stm32_usb_audio/blob/8bbd39be9ce847e85503d9603e999aa776704a4b/usb_audio.c#L425) cases. 

So maybe just delete the line [#415](https://github.com/anonymou8/stm32_usb_audio/blob/8bbd39be9ce847e85503d9603e999aa776704a4b/usb_audio.c#L415) with the `data = 1;` expression then? And we're done with `1.`.

**Comment by viteo** [comment]
1. solved
2. this change breaks descriptor. I also tried substract 1 from [`CD_TOTAL_SZ`](https://github.com/viteo/stm32_usb_audio/blob/f19ce994d50d66aaf0e44071071f6b332e0a4862/descriptors_audio.s#L189), but same result. The log shows that this skipped byte slip into the next descriptor. If we are not playing code golf, lets keep current version. Btw, binary in this case is smaller XD

**Comment by anonymou8** [comment]
> binary in this case is smaller XD

:) Btw, it was one of my goals when I was doing this project.

Made some edits. What do you think? Does it still work?

**Comment by viteo** [comment]
tested on both OSs. everything is cool

**Comment by anonymou8** [comment]
@viteo Thanks a lot, Viktar!

**Pull request merged**
